import { NextRequest, NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/server'
import { requireOrgAndUser } from '@/lib/auth'
import { getViewerScope, assertCapability } from '@/lib/rbac'
import { parseBody, handleSupabaseError } from '@/lib/api/helpers'
import { jobSendIntakeSchema } from '@/lib/validations/jobs'
import { sendEmail } from '@/lib/email/send'
import { renderIntakeInvite } from '@/lib/email/templates'
import type { SupabaseClient } from '@supabase/supabase-js'

const APP_URL = () => (process.env.NEXT_PUBLIC_APP_URL ?? 'https://recruiterstack.in').replace(/\/$/, '')

/** Find an org-scoped department by name, creating it if absent. */
async function findOrCreateDepartment(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: SupabaseClient<any>,
  orgId: string,
  name: string,
): Promise<string | null> {
  const trimmed = name.trim()
  if (!trimmed) return null
  const { data: existing } = await supabase
    .from('departments')
    .select('id')
    .eq('org_id', orgId)
    .eq('name', trimmed)
    .maybeSingle()
  if (existing) return (existing as { id: string }).id
  const { data: created } = await supabase
    .from('departments')
    .insert({ org_id: orgId, name: trimmed })
    .select('id')
    .single()
  return created ? (created as { id: string }).id : null
}

/**
 * POST /api/req-jobs/send-intake — "Send to Hiring Manager" path.
 *
 * Creates a draft job linked to an approved requisition, flags it as awaiting
 * the HM's input (custom_fields.intake.awaiting_hm = true), and emails the HM a
 * public /intake/<token> link so they can fill in the role details and generate
 * a draft JD. On submit the job flips to 'approved' (see submitCanonicalIntakeJob)
 * for the recruiter to review and publish.
 *
 * Mirrors the requisition-gate rules of POST /api/req-jobs: a job can only be
 * created from an APPROVED requisition (opening).
 */
export async function POST(req: NextRequest) {
  const auth = await requireOrgAndUser()
  if (auth instanceof NextResponse) return auth
  const { orgId, userId } = auth

  const denied = assertCapability(await getViewerScope(createAdminClient(), orgId, userId), 'recruiting:edit')
  if (denied) return denied

  const body = await parseBody(req, jobSendIntakeSchema)
  if (body instanceof NextResponse) return body

  const supabase = createAdminClient()

  // Same requisition gate as POST /api/req-jobs: a job can only be created from
  // an approved requisition (opening).
  if (!body.link_opening_id) {
    return NextResponse.json(
      { error: 'A job can only be created from an approved requisition. Pick an approved requisition first.' },
      { status: 422 },
    )
  }
  const { data: linkedOpening } = await supabase
    .from('openings')
    .select('id, status')
    .eq('id', body.link_opening_id)
    .eq('org_id', orgId)
    .maybeSingle()
  if (!linkedOpening) {
    return NextResponse.json({ error: 'Requisition not found.' }, { status: 404 })
  }
  if ((linkedOpening as { status: string }).status !== 'approved') {
    return NextResponse.json(
      { error: 'That requisition is not approved yet. A job can only be created from an approved requisition.' },
      { status: 422 },
    )
  }

  const departmentId = await findOrCreateDepartment(supabase, orgId, body.department)

  // Merge the flow-through/intake fields with the HM contact + the awaiting flag.
  const intakeBag: Record<string, unknown> = {
    ...body.intake,
    hiring_manager_name:  body.hiring_manager_name || null,
    hiring_manager_email: body.hiring_manager_email,
    awaiting_hm:          true,
  }

  // intake_token is auto-generated by the migration-069 trigger; read it back.
  // custom_fields / intake_token are not in the generated types yet — cast.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: job, error } = await (supabase as any)
    .from('jobs')
    .insert({
      org_id:          orgId,
      title:           body.title,
      department_id:   departmentId,
      confidentiality: body.confidentiality,
      custom_fields:   { intake: intakeBag },
      status:          'draft',
      created_by:      userId,
    })
    .select('id, title, intake_token')
    .single()

  if (error) return handleSupabaseError(error)
  const jobRow = job as { id: string; title: string; intake_token: string }

  // Link the approved requisition to the new job. Ignore duplicate link (PK).
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { error: linkErr } = await (supabase as any)
    .from('job_openings')
    .insert({ job_id: jobRow.id, opening_id: body.link_opening_id, linked_by: userId })
  if (linkErr && linkErr.code !== '23505') return handleSupabaseError(linkErr)

  const intakeUrl = `${APP_URL()}/intake/${jobRow.intake_token}`

  // Look up the recruiter's name for a friendlier email "from". Best-effort.
  let recruiterName: string | null = null
  const { data: me } = await supabase
    .from('users')
    .select('full_name')
    .eq('id', userId)
    .maybeSingle()
  if (me) recruiterName = (me as { full_name: string | null }).full_name ?? null

  // Email the HM the intake link. sendEmail silently no-ops (never throws) when
  // SendGrid isn't configured, so the flow still works — the recruiter can copy
  // the link from the confirmation UI. We report email_sent based on whether
  // SendGrid is configured so the UI can tell the recruiter what to expect.
  const emailConfigured = Boolean(process.env.SENDGRID_API_KEY)
  const { subject, html } = renderIntakeInvite({
    hiringManagerName: body.hiring_manager_name || null,
    recruiterName,
    positionTitle:     jobRow.title,
    intakeUrl,
  })
  await sendEmail({ to: body.hiring_manager_email, subject, html })

  return NextResponse.json(
    { data: { id: jobRow.id, title: jobRow.title }, intake_url: intakeUrl, email_sent: emailConfigured },
    { status: 201 },
  )
}
